### ISSUE TITLE
.dmg install for rakudo* 2016.10 on Mac  OS X fails on El Capitan

### ISSUE THREAD

**Issue by dmaestro** [perl6/user-experience#14]
Downloading from rakudo.org/downloads/star the following:
rakudo-star-2016.10.dmg              23-Oct-2016 10:39  9.3M

I had previously installed rakudo-star-2016.04 from .dmg and the install was flawless. Installing the above image resulted in the following errors, when starting perl6:

```
$ /Applications/Rakudo/bin/perl6 -v
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/Rakudo/lib/libmoar.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/Rakudo/lib/libmoar.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

The build targeting Sierra fails on El Capitan (10.11.5). Unexpectedly requiring an OS upgrade to run the installed app might be a stopper for a lot of people who are looking for the ease of installing Rakudo Star.

**Comment by zoffixznet** [comment]
@stmuk any ideas for this?

**Comment by coke** [comment]
I believe this issue was resolved when dmaestro updated the xcode command line tool installation  (a new version of xcode had been installed, but the command line tools were not updated)

**Comment by dmaestro** [comment]
No, that only allowed me to build Rakudo from source :-). I reattempted the Star install (to paste the output above) and got the same error.

**Comment by stmuk** [comment]
@dmaestro Apple seem to have handled the OS upgrade quite badly see https://irclog.perlgeek.de/perl6-dev/2016-10-22#i_13448521 I hadn't seen them break backward compat with binaries before either but I can reproduce your problem. I'm going to rename the current DMG to contain 10.12 as a quick fix and attempt to build one which works on 10.11 and lower.

**Comment by stmuk** [comment]
I built http://pl6anet.org/drop/rakudo-star-2016.10.1.dmg on 10.11 and hope it also works on 10.12

Please test!

I'd hope there is a config option for the compiler toolchain on 10.12 to create binaries which work on 10.11 but don't have access to a 10.12 system right now.

**Comment by dmaestro** [comment]
Looks great at first view on 10.11.5:
```
its-MacBook-Pro-DLS:install_images douglasschrag$ /Applications/Rakudo/bin/perl6 -v
This is Rakudo version 2016.10 built on MoarVM version 2016.10
implementing Perl 6.c.
```

**Comment by abraxxa** [comment]
I can porovide a MacBook Pro with 10.12 Sierra if you want me to test something.

**Comment by dmaestro** [comment]
@abraxxa just see that the install image @stmuk linked above for 2016.10.1 installs and runs properly on Sierra, that would help!

**Comment by abraxxa** [comment]
I can confirm that this build also works on 10.12.1.

**Comment by stmuk** [comment]
@abraxxa Thanks! I'll put the image up
